# This file was generated by GoReleaser. DO NOT EDIT.
cask "a9s" do
  version "3.48.0"

  on_macos do
    on_intel do
      sha256 "dddfc1a030d40fc95dbfb239cb762a5f0d9cec4c0e53397a28a74afcf63a4cf3"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c66843a5786c36082728f846fdcc7349f74e88bcdc8928b5312fac2ca2e5f11"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4938f6c84a933985f9d93f46d7c2eaff22037659db796989ad937e237e7ae62"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "404a69f38873217bf799b362bb2b6c8dbe6873c06e56cd32f94667181ca0311d"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a9s"
  desc "Terminal UI AWS Resource Manager"
  homepage "https://github.com/k2m30/a9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a9s"

  # No zap stanza required

end
