# This file was generated by GoReleaser. DO NOT EDIT.
cask "a9s" do
  version "3.47.0"

  on_macos do
    on_intel do
      sha256 "d954578609d895305326ec98218b890a7bbd00a09db844c07ec678930640f572"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f6fb87fadcca196987fe52b2e175561c7b37d15a87bc5044a3445b7537c7635"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "85f512b4e4b40a68d8d216fda5bf437b2e37da6f0e1b010ec84d096efbc23f48"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "109452f721faf3037b6fe21ec325c762f785babc8da47f4d82f97670d2701162"
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_linux_arm64.tar.gz"
    end
  end

  name "a9s"
  desc "Terminal UI AWS Resource Manager"
  homepage "https://github.com/k2m30/a9s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a9s"

  # No zap stanza required

end
