# This file was generated by GoReleaser. DO NOT EDIT.
cask "a9s" do
  name "a9s"
  desc "Terminal UI AWS Resource Manager"
  homepage "https://github.com/k2m30/a9s"
  version "3.0.0-alpha.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "a9s"

  on_macos do
    on_intel do
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_darwin_amd64.tar.gz"
      sha256 "1ba34c5afe9f854bd3a60ca830bcb3d1e7b2abc767ab253384f1a32f52976960"
    end
    on_arm do
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_darwin_arm64.tar.gz"
      sha256 "a7189d15b8838c1708f5872e7e3da6f297cd6c74f5d9ef3a95459d2f97d6359b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_linux_amd64.tar.gz"
      sha256 "672a53659e91d019ceb12d3be96df2078e343b041ee6fb9d7fb4bedc2701ee69"
    end
    on_arm do
      url "https://github.com/k2m30/a9s/releases/download/v#{version}/a9s_#{version}_linux_arm64.tar.gz"
      sha256 "a3dd88eb3e9595de4f7b4853131470fb625cdc12a41c8a8a46c4ad709f215226"
    end
  end

  # No zap stanza required
end
