# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A9s < Formula
  desc "Terminal UI AWS Resource Manager"
  homepage "https://github.com/k2m30/a9s"
  version "3.41.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k2m30/a9s/releases/download/v3.41.0/a9s_3.41.0_darwin_amd64.tar.gz"
      sha256 "530686bd58b2bfc1d5d4ba6b77ac23033b121307e21b7f63b97edc8fa0e8fd26"

      define_method(:install) do
        bin.install "a9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k2m30/a9s/releases/download/v3.41.0/a9s_3.41.0_darwin_arm64.tar.gz"
      sha256 "c233f369378b4b957fa02183e47adb633de286ce4df2ba182fd173367b13e9e1"

      define_method(:install) do
        bin.install "a9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k2m30/a9s/releases/download/v3.41.0/a9s_3.41.0_linux_amd64.tar.gz"
      sha256 "2d50e54f9cfc873b5438b2b29f28b7a96c3a6adc0d41b2b936be697924e3cebc"
      define_method(:install) do
        bin.install "a9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k2m30/a9s/releases/download/v3.41.0/a9s_3.41.0_linux_arm64.tar.gz"
      sha256 "94917e0e68f64d57d466debcf72406bd1a19162118d88f5ba8be8faa9ef4cd22"
      define_method(:install) do
        bin.install "a9s"
      end
    end
  end

  test do
    system "#{bin}/a9s", "--version"
  end
end
